INSERT INTO POST_CATEGORY 
VALUES (1, now(), 'watchlist');

INSERT INTO POST_CATEGORY 
VALUES (2, now(), 'critique');

INSERT INTO POST_CATEGORY 
VALUES (3, now(), 'news');

INSERT INTO POST_CATEGORY 
VALUES (4, now(), 'debate');