DELETE FROM public.post_movie;
DELETE FROM public.tags;
DELETE FROM public.comments;
DELETE FROM public.movies;
DELETE FROM public.posts;
DELETE FROM public.post_category;
DELETE FROM public.user_role;
DELETE FROM public.roles;
DELETE FROM public.users;