INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(28, 'Action') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(12, 'Adventure') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(16, 'Animation') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(35, 'Comedy') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(80, 'Crime') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(99, 'Documentary') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(18, 'Drama') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(10751, 'Family') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(14, 'Fantasy') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(36, 'History') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(27, 'Horror') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(10402, 'Music') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(9648, 'Mystery') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(10749, 'Romance') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(878, 'Science Fiction') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(10770, 'TV Movie') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(53, 'Thriller') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(10752, 'War') ;
INSERT INTO  public.movie_categories(tmdb_category_id, name) VALUES(37, 'Western') ;