-- feature/bajaLogica
ALTER TABLE USERS ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE POSTS ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE COMMENTS ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE;

-- feature/ProfilePic
ALTER TABLE USERS ADD COLUMN avatar_id INTEGER DEFAULT NULL;
ALTER TABLE USERS ADD CONSTRAINT fk_user_avatar FOREIGN KEY (avatar_id) REFERENCES IMAGES (image_id);

--feature/description
ALTER TABLE USERS ADD COLUMN description VARCHAR(400) DEFAULT NULL;
